library(R.utils)
library(magrittr)
library(tidyr)
library(dplyr)
library(stringr)
library(readr)
library(lubridate)
library(fs)
library(futile.logger)
library(curlconverter)
library(jsonlite)
library(httr)
library(ssh)

source(file = "src/prep_funcs.R", encoding = "UTF-8")

proc_gh_logs("Streams")
proc_gh_logs("RoD")
